# Generated by Django 6.0.6 on 2026-07-10 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0005_workspace_soft_delete_and_global_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('WORKSPACE_CREATED', 'Workspace created'), ('WORKSPACE_UPDATED', 'Workspace updated'), ('WORKSPACE_DELETED', 'Workspace deleted'), ('WORKSPACE_TRANSFERRED', 'Workspace transferred'), ('INVITATION_SENT', 'Invitation sent'), ('INVITATION_ACCEPTED', 'Invitation accepted'), ('INVITATION_REJECTED', 'Invitation rejected'), ('INVITATION_REVOKED', 'Invitation revoked'), ('INVITATION_EXPIRED', 'Invitation expired'), ('MEMBER_ROLE_CHANGED', 'Member role changed'), ('PROJECT_CREATED', 'Project created'), ('PROJECT_UPDATED', 'Project updated'), ('PROJECT_DELETED', 'Project deleted'), ('TASK_CREATED', 'Task created'), ('TASK_UPDATED', 'Task updated'), ('TASK_DELETED', 'Task deleted'), ('TASK_ASSIGNED', 'Task assigned'), ('TASK_UNASSIGNED', 'Task unassigned'), ('TASK_STATUS_CHANGED', 'Task status changed'), ('TASK_PRIORITY_CHANGED', 'Task priority changed'), ('TASK_DUE_DATE_CHANGED', 'Task due date changed'), ('COMMENT_CREATED', 'Comment created'), ('COMMENT_UPDATED', 'Comment updated'), ('COMMENT_DELETED', 'Comment deleted')], max_length=40)),
                ('description', models.TextField()),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='activities__workspa_32c6d5_idx'), models.Index(fields=['workspace', 'action'], name='activities__workspa_b6b846_idx'), models.Index(fields=['entity_type', 'entity_id'], name='activities__entity__da0f98_idx')],
            },
        ),
    ]
