# Generated by Django 6.0.6 on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("WORKSPACE_CREATED", "Workspace created"),
                    ("WORKSPACE_UPDATED", "Workspace updated"),
                    ("WORKSPACE_DELETED", "Workspace deleted"),
                    ("WORKSPACE_TRANSFERRED", "Workspace transferred"),
                    ("INVITATION_SENT", "Invitation sent"),
                    ("INVITATION_ACCEPTED", "Invitation accepted"),
                    ("INVITATION_REJECTED", "Invitation rejected"),
                    ("INVITATION_REVOKED", "Invitation revoked"),
                    ("INVITATION_EXPIRED", "Invitation expired"),
                    ("MEMBER_ROLE_CHANGED", "Member role changed"),
                    ("MEMBER_REMOVED", "Member removed"),
                    ("PROJECT_CREATED", "Project created"),
                    ("PROJECT_UPDATED", "Project updated"),
                    ("PROJECT_DELETED", "Project deleted"),
                    ("TASK_CREATED", "Task created"),
                    ("TASK_UPDATED", "Task updated"),
                    ("TASK_DELETED", "Task deleted"),
                    ("TASK_ASSIGNED", "Task assigned"),
                    ("TASK_UNASSIGNED", "Task unassigned"),
                    ("TASK_STATUS_CHANGED", "Task status changed"),
                    ("TASK_PRIORITY_CHANGED", "Task priority changed"),
                    ("TASK_DUE_DATE_CHANGED", "Task due date changed"),
                    ("COMMENT_CREATED", "Comment created"),
                    ("COMMENT_UPDATED", "Comment updated"),
                    ("COMMENT_DELETED", "Comment deleted"),
                ],
                max_length=40,
            ),
        ),
    ]
