# Generated by Django 6.0.6 on 2026-07-09 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='comments_co_task_id_354a70_idx',
            old_name='comments_co_task_id_579db6_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='comments_co_created_f73a6b_idx',
            old_name='comments_co_created_0a1189_idx',
        ),
    ]
